import 'package:flutter/foundation.dart';

/// Immutable data class describing a single hidden object in a level.
@immutable
class HiddenObject {
  /// Unique identifier — used as a map key and for debug logging.
  final String id;

  /// Human-readable display name (shown in future "found!" toast).
  final String name;

  /// Flutter asset path for the transparent-PNG sprite.
  final String assetPath;

  /// Horizontal position as a fraction of the canvas width (0.0 = left, 1.0 = right).
  final double xPercent;

  /// Vertical position as a fraction of the canvas height (0.0 = top, 1.0 = bottom).
  final double yPercent;

  /// Sprite render width as a fraction of the canvas width.
  final double widthPercent;

  /// Flutter asset path for the greyed-out and full-opacity thumbnail.
  final String thumbnailPath;

  const HiddenObject({
    required this.id,
    required this.name,
    required this.assetPath,
    required this.xPercent,
    required this.yPercent,
    required this.widthPercent,
    required this.thumbnailPath,
  });
}

const Map<int, List<HiddenObject>> kLevelObjects = {
  1: [
    HiddenObject(
      id: 'boomerang',
      name: 'Boomerang',
      assetPath: 'assets/images/sprite_boomerang.png',
      xPercent: 0.305,
      yPercent: 0.404,
      widthPercent: 0.24,
      thumbnailPath: 'assets/images/thumb_boomerang.png',
    ),
    HiddenObject(
      id: 'scarab',
      name: 'Scarab Beetle',
      assetPath: 'assets/images/sprite_scarab.png',
      xPercent: 0.878,
      yPercent: 0.105,
      widthPercent: 0.20,
      thumbnailPath: 'assets/images/thumb_scarab.png',
    ),
    HiddenObject(
      id: 'quill',
      name: 'Quill',
      assetPath: 'assets/images/sprite_quill.png',
      xPercent: 0.313,
      yPercent: 0.720,
      widthPercent: 0.20,
      thumbnailPath: 'assets/images/thumb_quill.png',
    ),
    HiddenObject(
      id: 'key',
      name: 'Antique Key',
      assetPath: 'assets/images/sprite_key.png',
      xPercent: 0.232,
      yPercent: 0.220,
      widthPercent: 0.18,
      thumbnailPath: 'assets/images/thumb_key.png',
    ),
    HiddenObject(
      id: 'gecko',
      name: 'Gecko',
      assetPath: 'assets/images/sprite_gecko.png',
      xPercent: 0.091,
      yPercent: 0.448,
      widthPercent: 0.20,
      thumbnailPath: 'assets/images/thumb_gecko.png',
    ),
    HiddenObject(
      id: 'compass',
      name: 'Brass Compass',
      assetPath: 'assets/images/sprite_compass.png',
      xPercent: 0.859,
      yPercent: 0.580,
      widthPercent: 0.18,
      thumbnailPath: 'assets/images/thumb_compass.png',
    ),
    HiddenObject(
      id: 'map',
      name: 'Parchment Map',
      assetPath: 'assets/images/sprite_map.png',
      xPercent: 0.470,
      yPercent: 0.761,
      widthPercent: 0.17,
      thumbnailPath: 'assets/images/thumb_map.png',
    ),
    HiddenObject(
      id: 'fossil',
      name: 'Amber Fossil',
      assetPath: 'assets/images/sprite_fossil.png',
      xPercent: 0.921,
      yPercent: 0.471,
      widthPercent: 0.14,
      thumbnailPath: 'assets/images/thumb_fossil.png',
    ),
    HiddenObject(
      id: 'journal',
      name: 'Leather Journal',
      assetPath: 'assets/images/sprite_journal.png',
      xPercent: 0.073,
      yPercent: 0.364,
      widthPercent: 0.17,
      thumbnailPath: 'assets/images/thumb_journal.png',
    ),
    HiddenObject(
      id: 'binoculars',
      name: 'Vintage Binoculars',
      assetPath: 'assets/images/sprite_binoculars.png',
      xPercent: 0.737,
      yPercent: 0.514,
      widthPercent: 0.18,
      thumbnailPath: 'assets/images/thumb_binoculars.png',
    ),
  ],
  2: [
    HiddenObject(
      id: 'potion',
      name: 'Teardrop Potion Bottle',
      assetPath: 'assets/images/sprite_potion.png',
      xPercent: 0.836,
      yPercent: 0.348,
      widthPercent: 0.12,
      thumbnailPath: 'assets/images/thumb_potion.png',
    ),
    HiddenObject(
      id: 'crystal',
      name: 'Swirling Crystal Ball',
      assetPath: 'assets/images/sprite_crystal.png',
      xPercent: 0.206,
      yPercent: 0.577,
      widthPercent: 0.14,
      thumbnailPath: 'assets/images/thumb_crystal.png',
    ),
    HiddenObject(
      id: 'mortar',
      name: 'Mortar and Glowing Pestle',
      assetPath: 'assets/images/sprite_mortar.png',
      xPercent: 0.490,
      yPercent: 0.214,
      widthPercent: 0.14,
      thumbnailPath: 'assets/images/thumb_mortar.png',
    ),
    HiddenObject(
      id: 'herbs',
      name: 'Bundle of Magical Herbs',
      assetPath: 'assets/images/sprite_herbs.png',
      xPercent: 0.792,
      yPercent: 0.621,
      widthPercent: 0.12,
      thumbnailPath: 'assets/images/thumb_herbs.png',
    ),
    HiddenObject(
      id: 'hat',
      name: 'Floppy Witch\'s Hat',
      assetPath: 'assets/images/sprite_hat.png',
      xPercent: 0.548,
      yPercent: 0.792,
      widthPercent: 0.14,
      thumbnailPath: 'assets/images/thumb_hat.png',
    ),
    HiddenObject(
      id: 'candle',
      name: 'Wax Candle',
      assetPath: 'assets/images/sprite_candle.png',
      xPercent: 0.130,
      yPercent: 0.721,
      widthPercent: 0.11,
      thumbnailPath: 'assets/images/thumb_candle.png',
    ),
    HiddenObject(
      id: 'scale',
      name: 'Gold Scale',
      assetPath: 'assets/images/sprite_scale.png',
      xPercent: 0.843,
      yPercent: 0.779,
      widthPercent: 0.16,
      thumbnailPath: 'assets/images/thumb_scale.png',
    ),
    HiddenObject(
      id: 'tarot',
      name: 'Moon Tarot Card',
      assetPath: 'assets/images/sprite_tarot.png',
      xPercent: 0.092,
      yPercent: 0.308,
      widthPercent: 0.13,
      thumbnailPath: 'assets/images/thumb_tarot.png',
    ),
    HiddenObject(
      id: 'wand',
      name: 'Wooden Wand',
      assetPath: 'assets/images/sprite_wand.png',
      xPercent: 0.473,
      yPercent: 0.412,
      widthPercent: 0.17,
      thumbnailPath: 'assets/images/thumb_wand.png',
    ),
    HiddenObject(
      id: 'sage',
      name: 'Sage Bundle',
      assetPath: 'assets/images/sprite_sage.png',
      xPercent: 0.819,
      yPercent: 0.189,
      widthPercent: 0.13,
      thumbnailPath: 'assets/images/thumb_sage.png',
    ),
  ],
  3: [
    HiddenObject(
      id: 'conductor_hat',
      name: 'Vintage Conductor\'s Hat',
      assetPath: 'assets/images/sprite_conductor_hat.png',
      xPercent: 0.746,
      yPercent: 0.599,
      widthPercent: 0.14,
      thumbnailPath: 'assets/images/thumb_conductor_hat.png',
    ),
    HiddenObject(
      id: 'bell',
      name: 'Antique Brass Trolley Bell',
      assetPath: 'assets/images/sprite_bell.png',
      xPercent: 0.462,
      yPercent: 0.419,
      widthPercent: 0.12,
      thumbnailPath: 'assets/images/thumb_bell.png',
    ),
    HiddenObject(
      id: 'pocket_watch',
      name: 'Golden Pocket Watch',
      assetPath: 'assets/images/sprite_pocket_watch.png',
      xPercent: 0.154,
      yPercent: 0.760,
      widthPercent: 0.10,
      thumbnailPath: 'assets/images/thumb_pocket_watch.png',
    ),
    HiddenObject(
      id: 'satchel',
      name: 'Weathered Traveler\'s Satchel',
      assetPath: 'assets/images/sprite_satchel.png',
      xPercent: 0.988,
      yPercent: 0.590,
      widthPercent: 0.16,
      thumbnailPath: 'assets/images/thumb_satchel.png',
    ),
    HiddenObject(
      id: 'lantern',
      name: 'Rusty Iron Lantern',
      assetPath: 'assets/images/sprite_lantern.png',
      xPercent: 0.122,
      yPercent: 0.480,
      widthPercent: 0.12,
      thumbnailPath: 'assets/images/thumb_lantern.png',
    ),
    HiddenObject(
      id: 'ticket',
      name: 'Trolley Ticket',
      assetPath: 'assets/images/sprite_ticket.png',
      xPercent: 0.596,
      yPercent: 0.599,
      widthPercent: 0.12,
      thumbnailPath: 'assets/images/thumb_ticket.png',
    ),
    HiddenObject(
      id: 'wrench',
      name: 'Iron Wrench',
      assetPath: 'assets/images/sprite_wrench.png',
      xPercent: 0.367,
      yPercent: 0.674,
      widthPercent: 0.18,
      thumbnailPath: 'assets/images/thumb_wrench.png',
    ),
    HiddenObject(
      id: 'whistle',
      name: "Conductor's Whistle",
      assetPath: 'assets/images/sprite_whistle.png',
      xPercent: 0.466,
      yPercent: 0.770,
      widthPercent: 0.11,
      thumbnailPath: 'assets/images/thumb_whistle.png',
    ),
    HiddenObject(
      id: 'nest',
      name: "Bird's Nest",
      assetPath: 'assets/images/sprite_nest.png',
      xPercent: 0.227,
      yPercent: 0.148,
      widthPercent: 0.16,
      thumbnailPath: 'assets/images/thumb_nest.png',
    ),
    HiddenObject(
      id: 'coin',
      name: 'Gold Coin',
      assetPath: 'assets/images/sprite_coin.png',
      xPercent: 0.907,
      yPercent: 0.754,
      widthPercent: 0.12,
      thumbnailPath: 'assets/images/thumb_coin.png',
    ),
  ],
  4: [
    HiddenObject(
      id: 'perfume',
      name: 'Jeweled Perfume Bottle',
      assetPath: 'assets/images/sprite_perfume.png',
      xPercent: 0.311,
      yPercent: 0.341,
      widthPercent: 0.11,
      thumbnailPath: 'assets/images/thumb_perfume.png',
    ),
    HiddenObject(
      id: 'mirror',
      name: 'Antique Hand Mirror',
      assetPath: 'assets/images/sprite_mirror.png',
      xPercent: 0.292,
      yPercent: 0.550,
      widthPercent: 0.14,
      thumbnailPath: 'assets/images/thumb_mirror.png',
    ),
    HiddenObject(
      id: 'necklace',
      name: 'Pearl and Ruby Necklace',
      assetPath: 'assets/images/sprite_necklace.png',
      xPercent: 0.023,
      yPercent: 0.217,
      widthPercent: 0.14,
      thumbnailPath: 'assets/images/thumb_necklace.png',
    ),
    HiddenObject(
      id: 'bow',
      name: 'Cobalt Velvet Hair Bow',
      assetPath: 'assets/images/sprite_bow.png',
      xPercent: 0.887,
      yPercent: 0.437,
      widthPercent: 0.11,
      thumbnailPath: 'assets/images/thumb_bow.png',
    ),
    HiddenObject(
      id: 'compact',
      name: 'Open Powder Compact',
      assetPath: 'assets/images/sprite_compact.png',
      xPercent: 0.151,
      yPercent: 0.743,
      widthPercent: 0.12,
      thumbnailPath: 'assets/images/thumb_compact.png',
    ),
    HiddenObject(
      id: 'hairbrush',
      name: 'Silver Hairbrush',
      assetPath: 'assets/images/sprite_hairbrush.png',
      xPercent: 0.374,
      yPercent: 0.807,
      widthPercent: 0.16,
      thumbnailPath: 'assets/images/thumb_hairbrush.png',
    ),
    HiddenObject(
      id: 'pearl',
      name: 'Pearl Earring',
      assetPath: 'assets/images/sprite_pearl.png',
      xPercent: 0.113,
      yPercent: 0.395,
      widthPercent: 0.12,
      thumbnailPath: 'assets/images/thumb_pearl.png',
    ),
    HiddenObject(
      id: 'slipper',
      name: 'Silk Slipper',
      assetPath: 'assets/images/sprite_slipper.png',
      xPercent: 0.663,
      yPercent: 0.510,
      widthPercent: 0.17,
      thumbnailPath: 'assets/images/thumb_slipper.png',
    ),
    HiddenObject(
      id: 'musicbox',
      name: 'Music Box',
      assetPath: 'assets/images/sprite_musicbox.png',
      xPercent: 0.716,
      yPercent: 0.692,
      widthPercent: 0.17,
      thumbnailPath: 'assets/images/thumb_musicbox.png',
    ),
    HiddenObject(
      id: 'teacup',
      name: 'Porcelain Teacup',
      assetPath: 'assets/images/sprite_teacup.png',
      xPercent: 0.059,
      yPercent: 0.348,
      widthPercent: 0.14,
      thumbnailPath: 'assets/images/thumb_teacup.png',
    ),
  ],
  5: [
    HiddenObject(
      id: 'acorn',
      name: 'Glowing Golden Acorn',
      assetPath: 'assets/images/sprite_acorn.png',
      xPercent: 0.878,
      yPercent: 0.078,
      widthPercent: 0.10,
      thumbnailPath: 'assets/images/thumb_acorn.png',
    ),
    HiddenObject(
      id: 'flute',
      name: 'Carved Fairy Flute',
      assetPath: 'assets/images/sprite_flute.png',
      xPercent: 0.332,
      yPercent: 0.590,
      widthPercent: 0.14,
      thumbnailPath: 'assets/images/thumb_flute.png',
    ),
    HiddenObject(
      id: 'leaf_cup',
      name: 'Dewdrop Leaf Cup',
      assetPath: 'assets/images/sprite_leaf_cup.png',
      xPercent: 0.821,
      yPercent: 0.488,
      widthPercent: 0.12,
      thumbnailPath: 'assets/images/thumb_leaf_cup.png',
    ),
    HiddenObject(
      id: 'snail',
      name: 'Swirling Magenta Snail Shell',
      assetPath: 'assets/images/sprite_snail.png',
      xPercent: 0.353,
      yPercent: 0.262,
      widthPercent: 0.11,
      thumbnailPath: 'assets/images/thumb_snail.png',
    ),
    HiddenObject(
      id: 'moth',
      name: 'Jewel-Toned Luna Moth',
      assetPath: 'assets/images/sprite_moth.png',
      xPercent: 0.092,
      yPercent: 0.106,
      widthPercent: 0.14,
      thumbnailPath: 'assets/images/thumb_moth.png',
    ),
    HiddenObject(
      id: 'berry',
      name: 'Magical Berry',
      assetPath: 'assets/images/sprite_berry.png',
      xPercent: 0.460,
      yPercent: 0.680,
      widthPercent: 0.11,
      thumbnailPath: 'assets/images/thumb_berry.png',
    ),
    HiddenObject(
      id: 'fairywing',
      name: 'Fairy Wing',
      assetPath: 'assets/images/sprite_fairywing.png',
      xPercent: 0.626,
      yPercent: 0.164,
      widthPercent: 0.17,
      thumbnailPath: 'assets/images/thumb_fairywing.png',
    ),
    HiddenObject(
      id: 'crystal_shard',
      name: 'Crystal Shard',
      assetPath: 'assets/images/sprite_crystal_shard.png',
      xPercent: 0.935,
      yPercent: 0.623,
      widthPercent: 0.14,
      thumbnailPath: 'assets/images/thumb_crystal_shard.png',
    ),
    HiddenObject(
      id: 'pinecone',
      name: 'Magical Pinecone',
      assetPath: 'assets/images/sprite_pinecone.png',
      xPercent: 0.107,
      yPercent: 0.071,
      widthPercent: 0.14,
      thumbnailPath: 'assets/images/thumb_pinecone.png',
    ),
    HiddenObject(
      id: 'dewdrop',
      name: 'Morning Dewdrop',
      assetPath: 'assets/images/sprite_dewdrop.png',
      xPercent: 0.154,
      yPercent: 0.650,
      widthPercent: 0.13,
      thumbnailPath: 'assets/images/thumb_dewdrop.png',
    ),
  ],
};

List<HiddenObject> getObjectsForLevel(int levelNumber) {
  return kLevelObjects[levelNumber] ?? [];
}
